---
apiVersion: v1
kind: Secret
metadata:
  name: tavily-search-key
  annotations:
    avp.kubernetes.io/path: "kv/data/ocp/ocp.ggwrt/llama-stack"
type: Opaque
stringData:
  tavily-search-api-key: <tavily-api-key>
